# docker-compose.yml (at root)

version: "3.9"

services:
# i am using neon db so docker postgres db is obsolete
  # db:
  #   image: postgres:16-alpine
  #   container_name: gymtracker-db
  #   restart: always
    
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: gymdb
    
  #   ports:
  #     - "5432:5432"
    
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
    
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: gymtracker-api
    restart: always
    
    ports:
      - "8000:8000"
    
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      RATE_LIMIT_LOGIN: ${RATE_LIMIT_LOGIN}
      RATE_LIMIT_DEFAULT: ${RATE_LIMIT_DEFAULT}
    
    volumes:
      - ./apps/api:/app
    
    env_file:
      - ./.env

    # (gives DB time to fully initialize)
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata: