"""expand exercise model

Revision ID: 39c9b70897c7
Revises: ac1516e20824
Create Date: 2026-05-09 01:40:35.720624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c9b70897c7'
down_revision: Union[str, Sequence[str], None] = 'ac1516e20824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('muscle_group', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('equipment', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('is_custom', sa.Boolean(), nullable=False))
    op.add_column('exercises', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'created_by')
    op.drop_column('exercises', 'is_custom')
    op.drop_column('exercises', 'description')
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'muscle_group')
    # ### end Alembic commands ###
