"""remove unique constraint from exercise name

Revision ID: 8505094f2848
Revises: 39c9b70897c7
Create Date: 2026-05-30 00:08:21.798843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8505094f2848'
down_revision: Union[str, Sequence[str], None] = '39c9b70897c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    # ### end Alembic commands ###
